<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../clslist.cs" />
    <Compile Include="../../loadcontext.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="$(MetadataLoadContextVersion)" />
  </ItemGroup>
</Project>
